#!/usr/bin/env bash

sudo rm /usr/share/applications/vscodium-handler.desktop
sudo cp vscodium-handler.desktop /usr/share/applications
sudo update-desktop-database

sudo rm /usr/local/bin/vscodium-handler
sudo cp vscodium-handler /usr/local/bin/
sudo chmod +x /usr/local/bin/vscodium-handler